### ISSUE TITLE
Fail to set progname to separate logs

### ISSUE THREAD

**Issue by DavidGamba** [nathanaelle/syslog5424#2]
I am using this library to send multiple programs to a syslog server (rsyslog).

For some reason I can't get this library to allow me to split the sent messages into multiple logs by setting `progname`.

In logback I normally do it like this:

````
<appender name="syslog" class="ch.qos.logback.classic.net.SyslogAppender">
    <syslogHost>IP</syslogHost>
    <port>514</port>
    <facility>USER</facility>
    <suffixPattern>progname[0]${layout}</suffixPattern>
</appender>
````

With syslog5424 I have tried a few things:

````
	conn, err := syslog5424.Dial(s.protocol, s.server)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	w, err := syslog5424.New(conn, s.priority, s.appname+"[0]")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	w.Channel(syslog5424.LOG_INFO).Log(fmt.Sprintf("%s[0] %s", s.appname, message))
	// w.Channel(syslog5424.LOG_INFO).Log(fmt.Sprintf("%s", message))
	conn.End()
````

But nothing seems to be working. I get all messages in a single log.

**Comment by nathanaelle** [comment]
in your snippet, the `s.priority` is a filtering priority … every message with a lesser priority is dropped.
if `s.priority` is the priority of a random log, you set it by creating a channel with this priority.

the `Channel` API is useful if you create a standalone application that may cope with several `*log.Logger`

In case of an syslog multiplexer, it's easier to use the `Sender.Send(Message)` because, you can take a custom `Message` and directly send it to your remote rsyslog.

with the code you provided the solution can be : 

```
sender, err := syslog5424.Dial(s.protocol, s.server)
if err != nil {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

for xmlog := range some_chan {
	sender.Send( syslog5424.CreateMessage( xmlog.appname, xmlog.priority, xmlog.message) )  
}

sender.End()

```

you must configure your rsyslog to accept rfc5424 messages, else it may be confused during the parsing.

**Comment by DavidGamba** [comment]
Thank you for your help and the awesome library. The only one we could get to work on both linux and windows :-)

My issue was related to rsyslog not properly populating `programname` (https://github.com/rsyslog/rsyslog/issues/1430).

Your code there helped me realize the problem wasn't with your library.

Thanks again!
